package com.sebone.deliveringsmiles.interfaces;

import java.util.List;

import com.sebone.deliveringsmiles.classes.OrderStatus;
import com.sebone.deliveringsmiles.classes.PayoutData;
/**class name:-DriverAddress
 * Objective:-This interface conatin 3 methods.we declare all the methods regarding payouts,like what is the amount of the money the  driver got from a particular order,what is the monthly payout generated by the driver and all the things.
 * @author Shraddha Choudhary
 * Date-24/03/2022
 */
public interface Payout {
	 PayoutData payoutByOrder(int orderId,int driverId);
	 List<PayoutData> payoutOfTheDays(OrderStatus orderStatus,int driverId ,String startDate,String endDate);
	 List<PayoutData> totalPayout(int driverId);
}
